### ISSUE TITLE
Naprawić README w /discord

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#20]
@TheJimmyNowak Jak implementował kod bota zmieniał menadżer paczek z pipa na poetry. I zapomniał zmienić README.md w folderze /discord.

README jest napisane w formacie .md (skrót od markdown) służy on do robienia ładnych plików tekstowych. Trzeba zmienić ten plik tak aby były w nim prawidłowe informacje do uruchamiania bota.

**TODO:**
- [x] Sklonować repozytorium (jeżeli nie jest sklonowane)
- [x] Wejść do folderu /discord
- [x] Stworzyć nowe środowisko poetry
- [x] Zainstalować wszystke paczki
- [x] Ustawić zmmienną środowiskową  (TOKEN=token-do-discorda) w pliku .env
- [x] Uruchomić kod przy użyciu docker-compose
- [x] Ładnie opisać powyższe kroki w README.md (razem z dokładnymi komendami które zostały wykonane)

**LINKI:**
- [Formatowanie markdowna](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
- [Dokumentacja Poetry](https://python-poetry.org/docs/)
- [Instalacja Dockera](https://docs.docker.com/desktop/install/windows-install/)
- [Docsy Docker compoe'a just in case](https://docs.docker.com/compose/)
