### ISSUE TITLE
Konfiguracji git hooks

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#24]
# Co trzeba zrobić
W naszym kodzie potrzebujemy narzędzi, które będą za nas dbały o to, żeby nasz kod był "Ładny". Te narzędzia będą odpalane przez tzw. git hooki.

# TODOs
- [x] Skonfigurować hook black'a
- [x] Skonfigurować hook ruff'a
- [x] Skonfigurować hook md linta
- [x] Sprawdzić, czy działa
- [x] Dokumentacja jak to zainstalować i jak to działa

# Kryterium akceptacji

Przy próbie commita kod automatycznie się sformatuje.

# Przydatne linki

- https://pre-commit.com/
- https://github.com/pre-commit/pre-commit-hooks
- https://github.com/python-poetry/poetry
- https://github.com/psf/black
- https://github.com/astral-sh/ruff-pre-commit
- https://github.com/DavidAnson/markdownlint-cli2
