### ISSUE TITLE
Stworzyć CONTRIBUTING.md

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#25]
# Co trzeba zrobić
Potrzebujemy plik CONTRIBUTING.md. Ten plik będzie czytała każda osoba, która zaczyna pracę w naszym projekcie. W pliku powinno się umieścić informacje jak wygląda proces dodawania zmian do projektu. Od przydzielenia taska do code review. Przy okazji w pliku powinno się wyjaśnić na czym polega github flow na którym będziemy działać. 

# TODOs
- [x] Opisać jak wygląda dodawanie zmian w naszym projekcie
- [x] Dodać linki do DC i projektu
- [x] Dodać info do kogo się zgłaszać w razie problemów
- [x] Opisać github flow (jak powinny wyglądać nazwy branchy, opisy PRów)

# Przydatne linki
- [Github Flow](https://docs.github.com/en/get-started/quickstart/github-flow)
- [What's COTRIBUTING.md](https://stackoverflow.com/questions/72929081/what-is-github-contributing-md-for)

**Comment by TheJimmyNowak** [comment]
W nawiązaniu do mojej rozmowy z @Karolingo dorzucam rzeczy do ogarnięcia:
- Co to jest commit (Jak je nazywać, jak często je robić)
- Co to jest branch i mergowanie (Jak je nazywać, jak mergować)
- Co to jest pull request (Co to code review?)
