### ISSUE TITLE
Przygotowanie serwera koła KNML

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#27]
# TODOs

- [x] Dołożenie RAMu i Dysków (częściowy fail, zamieniliśmy 2x8TB na 2x16TB bo tylko na tyle pozwalał workstation) 
- [x] Instalacja proxmoxa
- [x] PCI passthrough (żeby GPU działało w Virtualnych maszynach)
  - [x] Włączenie VT-D (czekamy na M.Cmila)
  - [x] Utworzenie VMki i test
 - [x] Przywrócenie Authentika (+ldapa) i WikiJS

**Comment by TheJimmyNowak** [comment]
Stoi nie opada
