### ISSUE TITLE
Zrobić folder z notebookami

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#52]
## Jaki jest cel tego tego zadania

Celem tego zadania jest testowanie, zapoznanie nas z nowymi technologiami oraz stworzenie wersji 0.0 nowych funkcjonalności, zwłaszcza dla parserów danych.

## Jak wygląda rozwiązanie?

Rozwiązanie powinno być w formie łatwej do eksperymentowania, testowania i przyswajania wiedzy, na przykład za pomocą notebooków <a target="_blank" href="https://colab.research.google.com/github/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/model_monitoring/model_monitoring.ipynb"> <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/> </a>  Na początek skupmy się na parserach danych.

## TODO:

- [x] Przygotować struktury folderów w repozytorium.
- [x] Stworzyć konfigurację za pomocą narzędzia Poetry, aby zapewnić spójność wersji.
- [x] Stworzyć parser danych dla stron internetowych.
- [x] Stworzyć parser danych dla WikiJS.
- [x] Stworzyć parser danych dla własnych dokumentów.

#75

**Comment by finloop** [comment]
Dodałbym:

- [ ] Open in google colab button <a target="_blank" href="https://colab.research.google.com/github/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/model_monitoring/model_monitoring.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>
