### ISSUE TITLE
Przygotować prezentację która podsumuje jak będzie wyglądać nasza aplikacja

### ISSUE THREAD

**Issue by TheJimmyNowak** [knmlprz/ChatKNML#53]
## Jaki jest cel tego zadania
Wprowadzenie osób początkujących w zawiłości naszej aplikacji oraz kolejna porcja sowitej nauki!

## Jak wygląda rozwiązanie?
Przygotowanie high-level summary architektury naszej aplikacji

## TODO:
- [x] Prezentacja przewidziana na 5 minut
- [x] Stworzyć wykresy dokładnie ilustrujące architekturę
- [x] Przygotować zwięzłe opisy poszczególnych elementów (Retriver, parser, dokument, frontend, api itd.) Muszą być jak najbardziej łopatologiczne. Są one skierowane do tych co nie mają doświadczenia
- [ ] Opowiedzieć czym jest README i słownik pojęć #47 

## Powiązane taski/bugi
#47 
#36 

## Linki:
- [Jakby ktoś niewidział zajebisty TedTalk](https://anontube.lvkaszus.pl/watch?v=Iwpi1Lm6dFo)
