### ISSUE TITLE
Baza danych sqlite dla benchmarków

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/ChatKNML#56]
## Jaki jest cel tego tego zadania

Stworzenie i konfiguracja bazy danych SQLite w kontekście benchmarków dla modeli (LLM), służącej do przechowywania data setów, wyników i danych związanych z benchmarkami

## Jak wygląda rozwiązanie?

Rozwiązanie polega na stworzeniu bazy danych SQLite w formie pliku, który zostanie umieszczony w repozytorium projektu. Baza danych będzie zawierać strukturę i dane potrzebne do przeprowadzania benchmarków.

## TODO

 - [ ] Utworzenie bazy danych SQLite
 - [ ] Określenie struktury bazy danych
 - [ ] Implementacja interfejsu do obsługi bazy
 - [ ] Integracja z benchmarkami LLM
