### ISSUE TITLE
User Benchmark Filtrujący Słabe Modele

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/ChatKNML#57]
## Jaki jest cel tego tego zadania

Celem tego zadania jest stworzenie benchmarku, który będzie służył do odfiltrowania LLM, które nie spełniają minimalnych oczekiwań, np. nie odpowiadają w języku polskim.

## Jak wygląda rozwiązanie?

Rozwiązanie polega na stworzeniu gotowego skryptu, który będzie działał w sposób ciągły. Skrypt ten będzie pobierał dane z bazy danych, przeprowadzał benchmark na bieżąco, rejestrował parametry, odpowiedzi modeli i przesyłał te dane do bazy danych.

## TODO:

- [ ] Określenie koncepcji testu
- [ ] Przygotowanie odpowiedniego zbioru danych
- [ ] Napisanie skryptu do przeprowadzania benchmarków
- [ ] Integracja skryptu z bazą danych

## Powiązane taski/bugi
#56
