### ISSUE TITLE
Benchmark Ilościowy w JP

### ISSUE THREAD

**Issue by Kleczyk** [knmlprz/ChatKNML#58]
## Jaki jest cel tego tego zadania

Ocena modelu na podstawie dużej ilości pytań w JP porówanie podobieństw odpowidzi LLM do oreginalnej

## Jak wygląda rozwiązanie?

Rozwiązanie polega na stworzeniu gotowego skryptu, który będzie działał w sposób ciągły. Skrypt ten będzie pobierał dane z bazy danych, przeprowadzał benchmark na bieżąco, rejestrował parametry, odpowiedzi modeli i przesyłał te dane do bazy danych.

## TODO:

- [ ] Określenie koncepcji testu
- [ ] Przygotowanie odpowiedniego zbioru danych
- [ ] Napisanie skryptu do przeprowadzania benchmarków
- [ ] Integracja skryptu z bazą danych

## Powiązane taski/bugi
#56
